version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "mypassword"
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0-beta.2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "RS256", "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxmW3lDkqs00ZGHY7xBZL\nKL3WVVpxqtLrvnhYo8MqzimNS1vZ5RvmPVoJ+kqB+tIDjUtxDHLCG2/ss77Pu/lV\ndB/5nSbTqJKO6ClwKwZ3rfIwhS6Ln/jEF1+V8EI7KN7IPLaLX386uNHTGUvukF26\nzqMS/ff8X4uQiMLTzA7ni0/bpZmSJSl/5Ae9l7vM2eI+tFZvz6XGg/Hk2vIhPfbp\ndIjSv7dPuOryui5IHCjcDbpivdqf6XymS4Xy5x4CtEakF0xFfD9RvJEsf+e5vk7Z\n0guxnYOUM9zNkwuye12gULfc4GCxFstTWw4Ecpbwl3+9VAuo72xJmy/w2lrWJxtp\nuwIDAQAB\n-----END PUBLIC KEY-----\n-" }'
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:mypassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "adminsecret"
volumes:
  db_data:
